# Generated by Django 2.1.7 on 2019-03-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190312_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license_number', models.CharField(max_length=255, null=True)),
                ('ambulance_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AmbulanceService')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='model',
            new_name='car_model',
        ),
    ]
