# Generated by Django 2.1.7 on 2019-03-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190320_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='health_service',
        ),
    ]
