# Generated by Django 2.1.7 on 2019-03-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190330_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDriverAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=255, null=True)),
                ('ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ambulance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AmbulanceDriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
