# Generated by Django 2.1.7 on 2019-04-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190402_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAmbulanceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ambulanceservice',
            name='is_for_health_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthambulanceservice',
            name='ambulance_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AmbulanceService'),
        ),
        migrations.AddField(
            model_name='healthambulanceservice',
            name='health_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.HealthService'),
        ),
    ]
