# Generated by Django 2.1.7 on 2019-08-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190802_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Available', max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('ambulance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ambulance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
