# Generated by Django 2.1.7 on 2019-08-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('init_from_lat', models.CharField(max_length=255, null=True)),
                ('init_to_lat', models.CharField(max_length=255, null=True)),
                ('init_from_long', models.CharField(max_length=255, null=True)),
                ('init_to_long', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('init_distance', models.CharField(max_length=255, null=True)),
                ('final_distance', models.CharField(max_length=255, null=True)),
                ('final_from_lat', models.CharField(max_length=255, null=True)),
                ('final_to_lat', models.CharField(max_length=255, null=True)),
                ('final_from_long', models.CharField(max_length=255, null=True)),
                ('final_to_long', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance', to='core.Ambulance')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='core.AuthUserDemographic')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
