# Generated by Django 2.1.7 on 2019-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_charge',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='init_charge',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
