# Generated by Django 2.1.7 on 2019-10-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190901_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='ambulance_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe')], max_length=255, null=True),
        ),
    ]
