# Generated by Django 2.1.7 on 2019-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ambulance_ambulance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerate',
            name='deluxe_rate',
            field=models.CharField(default='1', max_length=255, null=True),
        ),
    ]
